SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP DATABASE IF EXISTS `anuncios`;

CREATE DATABASE `anuncios`;

USE `anuncios`;

CREATE TABLE IF NOT EXISTS `anuncio` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `imagen` VARCHAR(255) NOT NULL,
    `link` VARCHAR(255) NOT NULL,
    `vecesClickado` INT DEFAULT 0,
    `tipo` INT,
    `nombre` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE anuncio (
     id INT AUTO_INCREMENT PRIMARY KEY,
     imagen VARCHAR(255) NOT NULL,
     link VARCHAR(255) NOT NULL,
     vecesClickado INT DEFAULT 0,
     tipo INT,
     nombre VARCHAR(255),

     FOREIGN KEY (tipo) REFERENCES tipo_anuncio(id) ON DELETE SET NULL
);


CREATE TABLE tipo_anuncio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL
);