<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container85Yeskf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container85Yeskf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container85Yeskf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container85Yeskf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container85Yeskf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '85Yeskf',
    'container.build_id' => '812b2993',
    'container.build_time' => 1742037544,
], __DIR__.\DIRECTORY_SEPARATOR.'Container85Yeskf');
